version: "3.9"
services:
   db:
      image: mysql:8
      restart: always
      environment:
         MYSQL_DATABASE: 'bootdb'
         MYSQL_ROOT_PASSWORD: 'root'
      container_name: mysql8
      networks:
         - mynetwork
      ports:
         - 3306:3306
         - 33060:33060

   api:
      image: lucasvilela/stock-manager:latest
      container_name: stock-manager
      restart: always
      networks:
         - mynetwork
      ports:
         - 8080:8080

   myproject:
      image: quotation-management:latest
      container_name: quotation-management-app
      restart: always
      networks:
         - mynetwork
      ports:
         - 8081:8081

networks:
   mynetwork:
      driver: bridge
